_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
uuid: 37cf889f-c3a1-4329-8b4c-7e65498a4b10
langcode: en
name: 'Cooking Recipes'
mail: camoa2005@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
